# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b467549be032d710a18c8e174daae93d"
name = "demo-download"
handle = "demo-download"
application_url = "https://present-expedia-trembl-murphy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-09aa42f9.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://present-expedia-trembl-murphy.trycloudflare.com/auth/callback",
  "https://present-expedia-trembl-murphy.trycloudflare.com/auth/shopify/callback",
  "https://present-expedia-trembl-murphy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
